/**
 * AutoAccountingEngine - Motor de Partida Doble Automática
 * 
 * Genera asientos contables automáticamente para cada transacción,
 * siguiendo estándares NIIF/IFRS y el plan de cuentas configurado.
 * 
 * Inspirado en SAP Business One y Alegra, pero simplificado para PYMES.
 */

import { db } from '$lib/server/db';
import { 
  journalEntries, 
  journalLines, 
  chartOfAccounts,
  type NewJournalEntry,
  type NewJournalLine 
} from '$lib/server/db/schema';
import { eq, and } from 'drizzle-orm';
import { MoneyUtils } from '$lib/server/utils/money-utils';

// ============================================
// TIPOS
// ============================================

export interface JournalEntryData {
  organizationId: string;
  branchId?: string;
  documentType: 'sale' | 'purchase' | 'expense' | 'payment' | 'receipt' | 'adjustment';
  documentId: string;
  description: string;
  reference?: string;
  transactionDate: number;
  lines: JournalLineData[];
  autoGenerated?: boolean;
  aiExplanation?: string;
  createdBy?: string;
}

export interface JournalLineData {
  accountCode: string; // Código de cuenta (ej: "1-01-001")
  description?: string;
  debitCents: number;
  creditCents: number;
  contactId?: string;
  productId?: string;
  branchId?: string;
}

export interface AccountingRule {
  documentType: string;
  lines: Array<{
    accountType: string;
    accountSubtype?: string;
    direction: 'debit' | 'credit';
    calculation: 'subtotal' | 'tax' | 'total' | 'fixed';
    fixedAmountCents?: number;
  }>;
}

// ============================================
// REGLAS CONTABLES POR DEFECTO
// ============================================

/**
 * Reglas contables automáticas por tipo de documento
 * Estas reglas generan los asientos basados en la transacción
 */
const ACCOUNTING_RULES: Record<string, AccountingRule> = {
  sale: {
    documentType: 'sale',
    lines: [
      { 
        accountType: 'asset', 
        accountSubtype: 'cash_accounts',
        direction: 'debit', 
        calculation: 'total' 
      },
      { 
        accountType: 'revenue', 
        accountSubtype: 'operating_revenue',
        direction: 'credit', 
        calculation: 'subtotal' 
      },
      { 
        accountType: 'liability', 
        accountSubtype: 'taxes_payable',
        direction: 'credit', 
        calculation: 'tax' 
      },
    ],
  },
  expense: {
    documentType: 'expense',
    lines: [
      { 
        accountType: 'expense', 
        direction: 'debit', 
        calculation: 'subtotal' 
      },
      { 
        accountType: 'asset', 
        accountSubtype: 'taxes_recoverable',
        direction: 'debit', 
        calculation: 'tax' 
      },
      { 
        accountType: 'asset', 
        accountSubtype: 'cash_accounts',
        direction: 'credit', 
        calculation: 'total' 
      },
    ],
  },
  payment: {
    documentType: 'payment',
    lines: [
      { 
        accountType: 'liability', 
        accountSubtype: 'accounts_payable',
        direction: 'debit', 
        calculation: 'total' 
      },
      { 
        accountType: 'asset', 
        accountSubtype: 'cash_accounts',
        direction: 'credit', 
        calculation: 'total' 
      },
    ],
  },
  receipt: {
    documentType: 'receipt',
    lines: [
      { 
        accountType: 'asset', 
        accountSubtype: 'cash_accounts',
        direction: 'debit', 
        calculation: 'total' 
      },
      { 
        accountType: 'asset', 
        accountSubtype: 'accounts_receivable',
        direction: 'credit', 
        calculation: 'total' 
      },
    ],
  },
};

// ============================================
// MOTOR DE ASIENTOS AUTOMÁTICOS
// ============================================

export class AutoAccountingEngine {
  
  /**
   * Crea un asiento contable automático para una venta
   */
  static async createSaleEntry(
    saleId: string,
    organizationId: string,
    branchId: string,
    subtotalCents: number,
    taxCents: number,
    totalCents: number,
    paymentMethod: string,
    userId?: string
  ): Promise<string> {
    
    // Determinar cuenta de caja según método de pago
    const cashAccountCode = this.getCashAccountCode(paymentMethod);
    
    const entryData: JournalEntryData = {
      organizationId,
      branchId,
      documentType: 'sale',
      documentId: saleId,
      description: `Venta automática - ${saleId}`,
      reference: saleId,
      transactionDate: Date.now(),
      autoGenerated: true,
      aiExplanation: 'Asiento generado automáticamente al registrar venta',
      createdBy: userId,
      lines: [
        {
          accountCode: cashAccountCode,
          description: 'Ingreso por venta',
          debitCents: totalCents,
          creditCents: 0,
        },
        {
          accountCode: '4-01-001', // Ingresos operativos
          description: 'Ingreso por ventas',
          debitCents: 0,
          creditCents: subtotalCents,
        },
        {
          accountCode: '2-02-001', // IVA por pagar
          description: 'IVA cobrado',
          debitCents: 0,
          creditCents: taxCents,
        },
      ],
    };
    
    return await this.createJournalEntry(entryData);
  }
  
  /**
   * Crea un asiento contable automático para un gasto
   */
  static async createExpenseEntry(
    expenseId: string,
    organizationId: string,
    branchId: string,
    subtotalCents: number,
    taxCents: number,
    totalCents: number,
    niifCategory: string,
    paymentMethod: string,
    userId?: string
  ): Promise<string> {
    
    const cashAccountCode = this.getCashAccountCode(paymentMethod);
    const expenseAccountCode = this.getExpenseAccountCode(niifCategory);
    
    const entryData: JournalEntryData = {
      organizationId,
      branchId,
      documentType: 'expense',
      documentId: expenseId,
      description: `Gasto automático - ${expenseId}`,
      reference: expenseId,
      transactionDate: Date.now(),
      autoGenerated: true,
      aiExplanation: 'Asiento generado automáticamente al registrar gasto',
      createdBy: userId,
      lines: [
        {
          accountCode: expenseAccountCode,
          description: 'Gasto registrado',
          debitCents: subtotalCents,
          creditCents: 0,
        },
        {
          accountCode: '1-03-001', // IVA por cobrar (crédito fiscal)
          description: 'IVA pagado',
          debitCents: taxCents,
          creditCents: 0,
        },
        {
          accountCode: cashAccountCode,
          description: 'Salida por gasto',
          debitCents: 0,
          creditCents: totalCents,
        },
      ],
    };
    
    return await this.createJournalEntry(entryData);
  }
  
  /**
   * Crea un asiento contable genérico
   */
  static async createJournalEntry(data: JournalEntryData): Promise<string> {
    // Validar que cuadre (debitos = créditos)
    const totalDebits = data.lines.reduce((sum, line) => sum + line.debitCents, 0);
    const totalCredits = data.lines.reduce((sum, line) => sum + line.creditCents, 0);
    
    if (totalDebits !== totalCredits) {
      throw new Error(
        `El asiento no cuadra. Débitos: ${MoneyUtils.formatMoney(totalDebits)}, ` +
        `Créditos: ${MoneyUtils.formatMoney(totalCredits)}`
      );
    }
    
    // Generar número de asiento
    const entryNumber = await this.generateEntryNumber(data.organizationId);
    
    // Insertar encabezado del asiento
    const newEntry: NewJournalEntry = {
      id: crypto.randomUUID(),
      entryNumber,
      organizationId: data.organizationId,
      branchId: data.branchId,
      transactionDate: data.transactionDate,
      postingDate: data.transactionDate,
      documentType: data.documentType,
      documentId: data.documentId,
      description: data.description,
      reference: data.reference,
      totalDebitsCents: totalDebits,
      totalCreditsCents: totalCredits,
      isPosted: 1, // Contabilizado inmediatamente
      isReversed: 0,
      autoGenerated: data.autoGenerated ? 1 : 0,
      aiExplanation: data.aiExplanation,
      createdBy: data.createdBy,
    };
    
    const [entry] = await db.insert(journalEntries).values(newEntry).returning();
    
    // Insertar líneas del asiento
    for (let i = 0; i < data.lines.length; i++) {
      const line = data.lines[i];
      const newLine: NewJournalLine = {
        id: crypto.randomUUID(),
        journalEntryId: entry.id,
        lineNumber: i + 1,
        accountId: await this.getAccountIdByCode(line.accountCode, data.organizationId),
        description: line.description || '',
        debitCents: line.debitCents,
        creditCents: line.creditCents,
        contactId: line.contactId,
        productId: line.productId,
        branchId: line.branchId || data.branchId,
      };
      
      await db.insert(journalLines).values(newLine);
    }
    
    return entry.id;
  }
  
  /**
   * Genera número consecutivo de asiento
   */
  private static async generateEntryNumber(organizationId: string): Promise<string> {
    const year = new Date().getFullYear();
    
    // Obtener último asiento del año
    const lastEntry = await db.query.journalEntries.findFirst({
      where: and(
        eq(journalEntries.organizationId, organizationId),
        eq(journalEntries.isReversed, 0)
      ),
      orderBy: (entries, { desc }) => [desc(entries.createdAt)],
    });
    
    let nextNumber = 1;
    if (lastEntry) {
      // Extraer número del último asiento
      const match = lastEntry.entryNumber.match(/-(\d+)$/);
      if (match) {
        nextNumber = parseInt(match[1]) + 1;
      }
    }
    
    return `ASIENTO-${year}-${String(nextNumber).padStart(5, '0')}`;
  }
  
  /**
   * Obtiene ID de cuenta por código
   */
  private static async getAccountIdByCode(code: string, organizationId: string): Promise<string> {
    const account = await db.query.chartOfAccounts.findFirst({
      where: and(
        eq(chartOfAccounts.accountCode, code),
        eq(chartOfAccounts.organizationId, organizationId)
      ),
    });
    
    if (!account) {
      // Crear cuenta por defecto si no existe
      throw new Error(`Cuenta contable ${code} no encontrada`);
    }
    
    return account.id;
  }
  
  /**
   * Obtiene código de cuenta de caja según método de pago
   */
  private static getCashAccountCode(paymentMethod: string): string {
    const mapping: Record<string, string> = {
      'cash': '1-01-001',      // Caja general
      'card': '1-02-001',      // Bancos
      'transfer': '1-02-002',  // Transferencias
      'sinpe': '1-02-003',     // SINPE Móvil
      'credit': '1-03-001',    // Cuentas por cobrar
    };
    
    return mapping[paymentMethod] || '1-01-001';
  }
  
  /**
   * Obtiene código de cuenta de gasto según categoría NIIF
   */
  private static getExpenseAccountCode(niifCategory: string): string {
    const mapping: Record<string, string> = {
      'cost_of_sales': '5-01-001',        // Costo de ventas
      'operating_expense': '6-01-001',    // Gastos operativos
      'employee_benefit': '6-02-001',     // Sueldos y salarios
      'depreciation': '6-03-001',         // Depreciación
      'financial_expense': '6-04-001',    // Gastos financieros
      'other_expense': '6-05-001',        // Otros gastos
      'non_operating_expense': '7-01-001',// Gastos no operativos
    };
    
    return mapping[niifCategory] || '6-01-001';
  }
  
  /**
   * Revierte/un asiento contable
   */
  static async reverseEntry(entryId: string, reason: string, userId?: string): Promise<string> {
    const originalEntry = await db.query.journalEntries.findFirst({
      where: eq(journalEntries.id, entryId),
      with: {
        lines: true,
      },
    });
    
    if (!originalEntry) {
      throw new Error('Asiento no encontrado');
    }
    
    if (originalEntry.isReversed) {
      throw new Error('El asiento ya está reversado');
    }
    
    // Crear asiento de reversión con débitos y créditos invertidos
    const reversalLines: JournalLineData[] = originalEntry.lines.map(line => ({
      accountCode: '', // Se obtendrá al crear
      description: `Reversión: ${line.description || ''}`,
      debitCents: line.creditCents,
      creditCents: line.debitCents,
    }));
    
    const reversalData: JournalEntryData = {
      organizationId: originalEntry.organizationId,
      branchId: originalEntry.branchId || undefined,
      documentType: 'adjustment',
      documentId: entryId,
      description: `Reversión de asiento ${originalEntry.entryNumber}: ${reason}`,
      reference: originalEntry.reference,
      transactionDate: Date.now(),
      lines: reversalLines,
      autoGenerated: false,
      aiExplanation: `Reversión manual: ${reason}`,
      createdBy: userId,
    };
    
    const reversalId = await this.createJournalEntry(reversalData);
    
    // Marcar asiento original como reversado
    await db.update(journalEntries)
      .set({
        isReversed: 1,
        reversedBy: reversalId,
        updatedAt: Date.now(),
      })
      .where(eq(journalEntries.id, entryId));
    
    return reversalId;
  }
  
  /**
   * Obtiene balance de comprobación para una organización
   */
  static async getTrialBalance(organizationId: string, fromDate: number, toDate: number) {
    const entries = await db.query.journalEntries.findMany({
      where: and(
        eq(journalEntries.organizationId, organizationId),
        eq(journalEntries.isPosted, 1),
        eq(journalEntries.isReversed, 0)
      ),
      with: {
        lines: {
          with: {
            account: true,
          },
        },
      },
    });
    
    // Agrupar saldos por cuenta
    const balances: Record<string, { debitCents: number; creditCents: number }> = {};
    
    for (const entry of entries) {
      if (entry.transactionDate < fromDate || entry.transactionDate > toDate) {
        continue;
      }
      
      for (const line of entry.lines) {
        if (!balances[line.accountId]) {
          balances[line.accountId] = { debitCents: 0, creditCents: 0 };
        }
        
        balances[line.accountId].debitCents += line.debitCents;
        balances[line.accountId].creditCents += line.creditCents;
      }
    }
    
    return Object.entries(balances).map(([accountId, balances]) => ({
      accountId,
      debitBalance: balances.debitCents - balances.creditCents,
      creditBalance: balances.creditCents - balances.debitCents,
    }));
  }
}

export default AutoAccountingEngine;
